class_name BuildingCatalog

## 建筑目录：所有建筑的静态配置，纯数据。
## 新增建筑 = 在这里加一条字典，不用改任何逻辑代码。
## cost / inputs / outputs 格式：[ [资源类型, 数量], ... ]
## workers = 需要的工人数（>0 时必须有村民在岗才生产/生效）
## housing = 提供住房容量；is_road = 按道路放置（不占建筑位）
## desc = 一句话作用说明（详情面板首行，让每个建筑的作用一目了然）
## aura_radius + aura_kind = 覆盖半径光环（"well"/"faith"/"fun"/"castle"，每日结算幸福）
## serves = 酒馆每天最多服务人数（耗啤酒）；auto_sells = 市场每天自动卖富余换金币
## auto_buys = [ [类型, 单价, 日上限], ... ] 贸易站用金币收购资源
## hp = 耐久（城墙/城门，可被强盗打坏）；is_wall = 城墙；is_gate = 城门（村民可走/敌人不可走）
## shoots_range / shoots_damage / shoots_interval = 箭塔射击（需在岗工人）
## trains_guards = 兵营：工人变卫兵；drag_place = 按住左键拖动连放
## needs_forest/mountain/berry = 选址需邻近对应资源地块
## work_radius = 工作区域半径（选中时画圈显示采集范围）
## depletes = "forest"：生产一轮消耗工作半径内一格森林（伐木场）
## plants = "forest"：生产一轮在周边种出一格森林（植树场）
## castle_bonus = 城堡：当前这一期给全体的幸福加成（升级用 crown 递增；满级才加冕）
## teach_radius / teach_slots = 学堂：点化半径与每日名额（改的是村民特长，不是幸福度，
##   所以刻意不走 aura_kind——它不该混进幸福度光环的结算循环）
## scares_wolves = 篝火：吓退野狼的半径（野狼不碰被照到的建筑，误入即逃）
## warms = 篝火：冬季烧固定木柴，替半径内所有住房集中取暖
## keeps_food = 粮仓：把生食保鲜线抬高多少（超线部分每天腐坏）
## no_winter = 冬季停产
## min_era = 解锁时代（建造菜单按此置灰）
## upgrade = 升级块 {cost(升 Lv2 造价，Lv3 = ×2), max_level, titles(Lv2/Lv3 名),
##   以及各项每级增量：speed 提速 / workers 工位 / housing 住房 / aura 光环 /
##   serves 服务 / sell_cap 日限 / buy_budget 收购预算 / hp 耐久 / radius 工作半径 /
##   damage 箭塔伤害 / range 箭塔射程 / keeps 粮仓保鲜量 / scare 篝火半径 /
##   teach_slots 学堂名额 / teach_radius 学堂半径 / crown 城堡幸福}；
##   生效值一律经 Building.eff_* 读取
## group = 建造菜单分组（food食物/resource资源/life民生/produce生产/defense防御）
## sector = 职能条线（military军事 / economy经济 / civic民生）：与 group 正交，
##   group 决定进哪个 Tab，sector 用来保证"每个时代都有军事/经济/民生可造"（logic_test 守）
## road_kind = 交通方式（dirt土路 / bridge木桥 / stone石板路 / pass山道），与 is_road 配套
## needs_clay / needs_iron = 选址需邻近黏土滩 / 铁矿脉
## 选址规则：建设用地只能是平原（草地）；森林/浆果丛是资源地块，不可建设

const R := ResourceManager.Type

const ALL: Array[Dictionary] = [
	{
		"id": &"road", "group": "resource", "sector": "economy", "name": "土路",
		"color": Color(0.72, 0.62, 0.45), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 1]], "is_road": true, "road_kind": "dirt", "drag_place": true,
		"desc": "村民走土路速度 +60%，寻路也会优先沿路走；可铺进森林成为林间小径",
	},
	{
		"id": &"house", "group": "life", "sector": "civic", "name": "小屋",
		"color": Color(0.75, 0.55, 0.35), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 5]],
		"produces": false, "housing": 3, "drag_place": true,
		"upgrade": {"cost": [[R.WOOD, 5]], "max_level": 3, "housing": 2,
			"titles": ["长屋", "宅院"]},
		"desc": "住 3 名村民：有房 +10 幸福，无家 -30；住房有空位且存粮够才会来新移民",
	},
	{
		"id": &"well", "group": "life", "sector": "civic", "name": "水井",
		"color": Color(0.4, 0.55, 0.7), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 3], [R.STONE, 2]],
		"produces": false, "aura_radius": 4.0, "aura_kind": "well",
		"upgrade": {"cost": [[R.WOOD, 2], [R.STONE, 3]], "max_level": 3, "aura": 1.5,
			"titles": ["石砌水井", "喷泉广场"]},
		"desc": "水井光环：半径 4 格内有住房的村民幸福 +5（无房者吃不到光环）",
	},
	{
		"id": &"gatherer", "group": "food", "sector": "economy", "name": "采集小屋",
		"color": Color(0.6, 0.45, 0.55), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 6]],
		"produces": true, "inputs": [], "outputs": [[R.FOOD, 2]],
		"interval": 9.0, "needs_berry": true, "no_winter": true, "workers": 1,
		"work_radius": 2.0,
		"upgrade": {"cost": [[R.WOOD, 6]], "max_level": 3, "speed": 0.4, "workers": 1, "radius": 1.0,
			"titles": ["采集工坊", "采集营地"]},
		"desc": "从浆果丛采集生食（冬季停产）；选中可查看采集范围",
	},
	{
		"id": &"fisher", "group": "food", "sector": "economy", "name": "渔屋",
		"color": Color(0.3, 0.5, 0.65), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 7]],
		"produces": true, "inputs": [], "outputs": [[R.FOOD, 2]],
		"interval": 10.0, "needs_water": true, "workers": 1,
		"work_radius": 2.0,
		"upgrade": {"cost": [[R.WOOD, 7]], "max_level": 3, "speed": 0.4, "workers": 1, "radius": 1.0,
			"titles": ["渔栈", "渔港"]},
		"desc": "在水边捕鱼产生食（全年不停产，冬天靠它续粮）；需邻近水域",
	},
	{
		"id": &"lumber", "group": "resource", "sector": "economy", "name": "伐木场",
		"color": Color(0.45, 0.3, 0.15), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 8]],
		"produces": true, "inputs": [], "outputs": [[R.WOOD, 2]],
		"interval": 5.0, "needs_forest": true, "workers": 2,
		"work_radius": 3.0, "depletes": "forest", "depletes_every": 10,
		"upgrade": {"cost": [[R.WOOD, 10]], "max_level": 3, "speed": 0.3, "workers": 1, "radius": 1.0,
			"titles": ["伐木工坊", "林场"]},
		"desc": "每产约 10 轮（约 20 木材）砍掉工作范围内一格森林；砍光停产，用植树场补种",
	},
	{
		"id": &"farm", "group": "food", "sector": "economy", "name": "麦田",
		"color": Color(0.85, 0.75, 0.3), "size": Vector2i(2, 2),
		"cost": [[R.WOOD, 4]],
		"produces": true, "inputs": [], "outputs": [[R.WHEAT, 2]],
		"interval": 8.0, "converts_to_farm": true, "no_winter": true, "workers": 2,
		"drag_place": true,
		"upgrade": {"cost": [[R.WOOD, 6]], "max_level": 3, "speed": 0.4, "workers": 1,
			"titles": ["轮作麦田", "灌溉麦田"]},
		"desc": "把草地犁成耕地产小麦（冬季停产）；只能建在平原上，拆除后复垦为草地",
	},
	{
		"id": &"quarry", "group": "resource", "sector": "economy", "name": "采石场",
		"color": Color(0.5, 0.5, 0.55), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 10]],
		"produces": true, "inputs": [], "outputs": [[R.STONE, 1]],
		"interval": 8.0, "needs_mountain": true, "workers": 1,
		"work_radius": 2.0,
		"upgrade": {"cost": [[R.WOOD, 10], [R.STONE, 4]], "max_level": 3, "speed": 0.5, "workers": 1, "radius": 1.0,
			"titles": ["石场", "大采石场"]},
		"desc": "开采石料（磨坊/面包房/水井/箭塔都要石头）；需邻近石林，选中可查看开采范围",
	},
	{
		"id": &"nursery", "group": "resource", "sector": "economy", "name": "植树场",
		"color": Color(0.3, 0.55, 0.25), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 10]],
		"produces": true, "inputs": [], "outputs": [],
		"interval": 12.0, "workers": 1,
		"work_radius": 3.0, "plants": "forest",
		"upgrade": {"cost": [[R.WOOD, 8]], "max_level": 2, "speed": 0.5, "radius": 1.0,
			"titles": ["苗圃"]},
		"desc": "每隔一段时间在周边草地种出一格森林，让伐木可持续；建议建在伐木场旁",
	},
	{
		"id": &"mill", "group": "food", "sector": "economy", "name": "磨坊",
		"color": Color(0.7, 0.7, 0.65), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 15], [R.STONE, 5]],
		"produces": true, "inputs": [[R.WHEAT, 2]], "outputs": [[R.FLOUR, 2]],
		"interval": 6.0, "workers": 1, "min_era": 2,
		"upgrade": {"cost": [[R.WOOD, 10], [R.STONE, 4]], "max_level": 3, "speed": 0.5, "workers": 1,
			"titles": ["双轮磨坊", "水力磨坊"]},
		"desc": "把小麦磨成面粉（面包链中间环节）",
	},
	{
		"id": &"bakery", "group": "food", "sector": "economy", "name": "面包房",
		"color": Color(0.8, 0.5, 0.3), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 20], [R.STONE, 6]],
		"produces": true, "inputs": [[R.FLOUR, 2]], "outputs": [[R.BREAD, 2]],
		"interval": 6.0, "workers": 1, "min_era": 2,
		"upgrade": {"cost": [[R.WOOD, 12], [R.STONE, 5]], "max_level": 3, "speed": 0.5, "workers": 1,
			"titles": ["大面包房", "面包工场"]},
		"desc": "把面粉烤成面包：面包回满饥饿度（生食只回一半），还 +10 幸福",
	},
	{
		"id": &"granary", "group": "food", "sector": "civic", "name": "粮仓",
		"color": Color(0.72, 0.6, 0.38), "size": Vector2i(2, 2),
		"cost": [[R.WOOD, 12], [R.STONE, 2]],
		"produces": false, "min_era": 2, "keeps_food": 40,
		"upgrade": {"cost": [[R.WOOD, 10], [R.STONE, 2]], "max_level": 3, "keeps": 40,
			"titles": ["大粮仓", "谷仓群"]},
		"desc": "把生食的保鲜线抬高 40（每级 +40）：超过保鲜线的生食每天会腐坏 20%，粮仓让你存得住余粮",
	},
	# ---- 时代Ⅰ 追加：狩猎/黏土的原料线，以及第一批军事与民生 ----
	{
		"id": &"hunter", "group": "food", "sector": "economy", "name": "猎人小屋",
		"color": Color(0.5, 0.38, 0.28), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 8]],
		"produces": true, "inputs": [], "outputs": [[R.MEAT, 1], [R.HIDE, 1]],
		"interval": 9.0, "needs_forest": true, "workers": 1,
		"work_radius": 3.0,
		"upgrade": {"cost": [[R.WOOD, 8]], "max_level": 3, "speed": 0.4, "workers": 1, "radius": 1.0,
			"titles": ["猎户营", "狩猎行"]},
		"desc": "在林中狩猎，同时产肉类与兽皮：肉比生食顶饿（回 80），兽皮是皮革链的源头",
	},
	{
		"id": &"clay_pit", "group": "resource", "sector": "economy", "name": "黏土坑",
		"color": Color(0.68, 0.48, 0.32), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 6]],
		"produces": true, "inputs": [], "outputs": [[R.CLAY, 2]],
		"interval": 8.0, "needs_clay": true, "workers": 1,
		"work_radius": 2.0,
		"upgrade": {"cost": [[R.WOOD, 8]], "max_level": 3, "speed": 0.5, "workers": 1, "radius": 1.0,
			"titles": ["大黏土坑", "陶土场"]},
		"desc": "在河滩黏土上挖土（砖窑的原料）；需邻近黏土滩",
	},
	{
		"id": &"elder_hut", "group": "life", "sector": "civic", "name": "村长木屋",
		"color": Color(0.7, 0.62, 0.42), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 8]],
		"produces": false, "aura_radius": 4.0, "aura_kind": "health",
		"upgrade": {"cost": [[R.WOOD, 6]], "max_level": 3, "aura": 1.5,
			"titles": ["村公所", "议事厅"]},
		"desc": "医护光环：半径 4 格内有住房的村民幸福 +6；时代Ⅳ起覆盖不到的人 -5",
	},
	{
		"id": &"palisade", "group": "defense", "sector": "military", "name": "木栅栏",
		"color": Color(0.5, 0.38, 0.22), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 2]],
		"hp": 35, "is_wall": true, "drag_place": true,
		"upgrade": {"cost": [[R.WOOD, 3]], "max_level": 2, "hp": 25,
			"titles": ["加固木栅"]},
		"desc": "开荒期的临时围挡（耐久 35）：拦不住铁了心的强盗，但足够把野狼逼去绕路",
	},
	{
		"id": &"lookout", "group": "defense", "sector": "military", "name": "警戒哨",
		"color": Color(0.62, 0.5, 0.32), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 6]],
		"produces": false, "workers": 1, "scares_wolves": 4.0,
		"upgrade": {"cost": [[R.WOOD, 5]], "max_level": 3, "scare": 1.5,
			"titles": ["哨楼", "望楼"]},
		"desc": "有人值守时半径 4 格内野狼不敢靠近；不烧柴，是篝火之前唯一的驱狼手段",
	},
	# ---- 时代Ⅱ：衣服链 ----
	{
		"id": &"pasture", "group": "produce", "sector": "economy", "name": "牧羊场",
		"color": Color(0.85, 0.82, 0.7), "size": Vector2i(2, 2),
		"cost": [[R.WOOD, 12]],
		"produces": true, "inputs": [], "outputs": [[R.WOOL, 2], [R.MEAT, 1]],
		"interval": 10.0, "workers": 1, "min_era": 2,
		"upgrade": {"cost": [[R.WOOD, 10]], "max_level": 3, "speed": 0.4, "workers": 1,
			"titles": ["大牧场", "高地牧场"]},
		"desc": "放牧同时产羊毛与肉类：衣服链的源头，也是第一条稳定的高热量食物线",
	},
	{
		"id": &"weaver", "group": "produce", "sector": "economy", "name": "纺织坊",
		"color": Color(0.7, 0.5, 0.6), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 15], [R.STONE, 5]],
		"produces": true, "inputs": [[R.WOOL, 2]], "outputs": [[R.CLOTHES, 1]],
		"interval": 6.0, "workers": 1, "min_era": 2,
		"upgrade": {"cost": [[R.WOOD, 10], [R.STONE, 4]], "max_level": 3, "speed": 0.5, "workers": 1,
			"titles": ["织坊", "织造工场"]},
		"desc": "羊毛织成衣服；时代Ⅱ起每天清晨自动给没衣服的村民发一件（+10 幸福）",
	},
	{
		"id": &"stall", "group": "produce", "sector": "economy", "name": "货摊",
		"color": Color(0.8, 0.72, 0.45), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 10], [R.STONE, 2]],
		"produces": false, "workers": 1, "min_era": 2, "auto_sells": true,
		"sell_cap": 8,
		"upgrade": {"cost": [[R.WOOD, 8], [R.STONE, 2]], "max_level": 3, "sell_cap": 6,
			"titles": ["集市摊", "小集市"]},
		"desc": "小型集市：每天自动卖保留线以上的富余产物，上限 8 金（时代Ⅳ的市场是它的大号版）",
	},
	{
		"id": &"bonfire", "group": "defense", "sector": "military", "name": "篝火",
		"color": Color(0.92, 0.5, 0.2), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 5]],
		"produces": false, "min_era": 2, "scares_wolves": 5.0, "warms": true,
		"drag_place": true,
		"upgrade": {"cost": [[R.WOOD, 4]], "max_level": 3, "scare": 1.5,
			"titles": ["火塘", "瞭望篝火"]},
		"desc": "半径 5 格：野狼不敢靠近被火照到的建筑；冬季每天烧 2 木，替范围内所有住房集中取暖（比每户各烧一份省得多）",
	},
	# ---- 时代Ⅱ 追加：蜂蜜与木炭、澡堂与猎犬，外加第一种跨水交通 ----
	{
		"id": &"bridge", "group": "resource", "sector": "economy", "name": "木桥",
		"color": Color(0.55, 0.38, 0.22), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 3]], "is_road": true, "road_kind": "bridge",
		"drag_place": true, "min_era": 2,
		"desc": "架在水域上一格一格连成桥（移速 ×1.25）：湖沼地形的生命线。注意强盗也会走桥",
	},
	{
		"id": &"apiary", "group": "food", "sector": "economy", "name": "养蜂场",
		"color": Color(0.9, 0.78, 0.35), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 10]],
		"produces": true, "inputs": [], "outputs": [[R.HONEY, 1]],
		"interval": 12.0, "needs_forest": true, "no_winter": true, "workers": 1,
		"min_era": 2, "work_radius": 3.0,
		"upgrade": {"cost": [[R.WOOD, 8]], "max_level": 3, "speed": 0.4, "workers": 1,
			"titles": ["蜂场", "蜜园"]},
		"desc": "林边采蜜（冬季停产）：蜂蜜回 60 饥饿且不腐坏，还是市场上的高价货",
	},
	{
		"id": &"charcoal_kiln", "group": "resource", "sector": "economy", "name": "炭窑",
		"color": Color(0.35, 0.32, 0.3), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 12], [R.STONE, 4]],
		"produces": true, "inputs": [[R.WOOD, 3]], "outputs": [[R.CHARCOAL, 2]],
		"interval": 8.0, "workers": 1, "min_era": 2,
		"upgrade": {"cost": [[R.WOOD, 10], [R.STONE, 4]], "max_level": 3, "speed": 0.5, "workers": 1,
			"titles": ["双膛炭窑", "炭场"]},
		"desc": "烧木材出木炭：砖窑与冶铁炉的燃料，整条重工业链的第一环",
	},
	{
		"id": &"bathhouse", "group": "life", "sector": "civic", "name": "公共浴场",
		"color": Color(0.55, 0.72, 0.78), "size": Vector2i(2, 2),
		"cost": [[R.WOOD, 14], [R.STONE, 10]],
		"produces": false, "workers": 1, "min_era": 2,
		"needs_water": true, "aura_radius": 6.0, "aura_kind": "health",
		"upgrade": {"cost": [[R.WOOD, 10], [R.STONE, 8]], "max_level": 3, "aura": 1.5,
			"titles": ["石砌浴场", "大浴场"]},
		"desc": "医护光环：半径 6 格内有住房的村民幸福 +6（需有人在岗）；建在水边",
	},
	{
		"id": &"kennel", "group": "defense", "sector": "military", "name": "猎犬棚",
		"color": Color(0.6, 0.42, 0.3), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 12], [R.MEAT, 4]],
		"produces": false, "workers": 1, "min_era": 2, "scares_wolves": 7.0,
		"upgrade": {"cost": [[R.WOOD, 8], [R.MEAT, 4]], "max_level": 3, "scare": 1.5,
			"titles": ["犬舍", "猎犬场"]},
		"desc": "半径 7 格野狼不敢靠近，比篝火范围更大且不烧柴；造价要用肉喂狗",
	},
	# ---- 时代Ⅲ：信仰与娱乐 ----
	{
		"id": &"church", "group": "life", "sector": "civic", "name": "教堂",
		"color": Color(0.9, 0.85, 0.6), "size": Vector2i(2, 2),
		"cost": [[R.WOOD, 20], [R.STONE, 15]],
		"produces": false, "workers": 1, "min_era": 3,
		"aura_radius": 6.0, "aura_kind": "faith",
		"upgrade": {"cost": [[R.WOOD, 15], [R.STONE, 12]], "max_level": 3, "aura": 1.5,
			"titles": ["石砌教堂", "大教堂"]},
		"desc": "信仰光环：半径 6 格内有住房的村民幸福 +10，覆盖不到 -5（需有人在岗）",
	},
	{
		"id": &"brewery", "group": "produce", "sector": "economy", "name": "酿酒坊",
		"color": Color(0.6, 0.4, 0.2), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 15], [R.STONE, 5]],
		"produces": true, "inputs": [[R.WHEAT, 2]], "outputs": [[R.BEER, 2]],
		"interval": 8.0, "workers": 1, "min_era": 3, "no_winter": true,
		"upgrade": {"cost": [[R.WOOD, 10], [R.STONE, 4]], "max_level": 3, "speed": 0.5, "workers": 1,
			"titles": ["大酿酒坊", "酒厂"]},
		"desc": "把小麦酿成啤酒供酒馆（冬季停产）；过剩的啤酒也能在市场卖钱",
	},
	{
		"id": &"tavern", "group": "life", "sector": "civic", "name": "酒馆",
		"color": Color(0.75, 0.45, 0.25), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 20], [R.STONE, 10]],
		"produces": false, "workers": 1, "min_era": 3,
		"aura_radius": 5.0, "aura_kind": "fun", "serves": 8,
		"upgrade": {"cost": [[R.WOOD, 15], [R.STONE, 8]], "max_level": 3, "aura": 1.0, "serves": 6,
			"titles": ["大酒馆", "客栈"]},
		"desc": "娱乐光环：半径 5 格内村民幸福 +10（覆盖不到 -5）；服务消耗啤酒，上限随时代扩容",
	},
	{
		"id": &"school", "group": "life", "sector": "civic", "name": "学堂",
		"color": Color(0.62, 0.72, 0.85), "size": Vector2i(2, 2),
		"cost": [[R.WOOD, 18], [R.STONE, 10]],
		"produces": false, "workers": 1, "min_era": 3,
		"teach_radius": 6.0, "teach_slots": 1,
		"upgrade": {"cost": [[R.WOOD, 14], [R.STONE, 8]], "max_level": 3,
			"teach_slots": 1, "teach_radius": 1.5, "titles": ["书院", "学宫"]},
		"desc": "每天清晨点化半径 6 格内的一名村民：体弱的调理成寻常，寻常的学会一门手艺（勤劳/手巧/腿快）；需先生在岗",
	},
	# ---- 时代Ⅲ 追加：砖/皮革/盐/药四条加工链，民兵与烽火，石板路 ----
	{
		"id": &"stone_road", "group": "resource", "sector": "economy", "name": "石板路",
		"color": Color(0.62, 0.62, 0.66), "size": Vector2i(1, 1),
		"cost": [[R.STONE, 1], [R.WOOD, 1]], "is_road": true, "road_kind": "stone",
		"drag_place": true, "min_era": 3,
		"desc": "移速 ×2.1（土路只有 ×1.6），寻路也更愿意走：可以直接盖在旧土路上升级",
	},
	{
		"id": &"brick_kiln", "group": "resource", "sector": "economy", "name": "砖窑",
		"color": Color(0.75, 0.42, 0.3), "size": Vector2i(2, 2),
		"cost": [[R.WOOD, 16], [R.STONE, 8]],
		"produces": true, "inputs": [[R.CLAY, 2], [R.CHARCOAL, 1]], "outputs": [[R.BRICK, 2]],
		"interval": 9.0, "workers": 2, "min_era": 3,
		"upgrade": {"cost": [[R.WOOD, 12], [R.STONE, 8]], "max_level": 3, "speed": 0.5, "workers": 1,
			"titles": ["大砖窑", "砖厂"]},
		"desc": "黏土加木炭烧成砖：石屋、医馆、棱堡都吃砖，是从木头城迈向石头城的门槛",
	},
	{
		"id": &"tannery", "group": "produce", "sector": "economy", "name": "制革坊",
		"color": Color(0.6, 0.45, 0.3), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 14], [R.STONE, 6]],
		"produces": true, "inputs": [[R.HIDE, 2]], "outputs": [[R.LEATHER, 1]],
		"interval": 8.0, "workers": 1, "min_era": 3,
		"upgrade": {"cost": [[R.WOOD, 10], [R.STONE, 5]], "max_level": 3, "speed": 0.5, "workers": 1,
			"titles": ["大制革坊", "皮革工场"]},
		"desc": "兽皮鞣成皮革：市场上 4 金一件的硬通货，也是骑士营的装备原料",
	},
	{
		"id": &"salt_works", "group": "resource", "sector": "economy", "name": "盐场",
		"color": Color(0.88, 0.88, 0.84), "size": Vector2i(2, 2),
		"cost": [[R.WOOD, 12], [R.STONE, 6]],
		"produces": true, "inputs": [], "outputs": [[R.SALT, 2]],
		"interval": 10.0, "needs_water": true, "no_winter": true, "workers": 1, "min_era": 3,
		"upgrade": {"cost": [[R.WOOD, 10], [R.STONE, 5]], "max_level": 3, "speed": 0.5, "workers": 1,
			"titles": ["大盐场", "盐田"]},
		"desc": "水边晒盐（冬季停产）：盐本身不能吃，但腌肉坊靠它把易腐的肉变成耐存的粮",
	},
	{
		"id": &"curing_house", "group": "food", "sector": "economy", "name": "腌肉坊",
		"color": Color(0.72, 0.42, 0.38), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 14], [R.STONE, 4]],
		"produces": true, "inputs": [[R.MEAT, 2], [R.SALT, 1]], "outputs": [[R.CURED_MEAT, 2]],
		"interval": 8.0, "workers": 1, "min_era": 3,
		"upgrade": {"cost": [[R.WOOD, 10], [R.STONE, 4]], "max_level": 3, "speed": 0.5, "workers": 1,
			"titles": ["大腌肉坊", "腌制工场"]},
		"desc": "肉加盐腌成腌肉：回 90 饥饿且永不腐坏——把夏天的肉存到冬天全靠它",
	},
	{
		"id": &"herb_garden", "group": "resource", "sector": "economy", "name": "草药园",
		"color": Color(0.45, 0.68, 0.42), "size": Vector2i(2, 2),
		"cost": [[R.WOOD, 10]],
		"produces": true, "inputs": [], "outputs": [[R.HERB, 2]],
		"interval": 10.0, "no_winter": true, "workers": 1, "min_era": 3,
		"upgrade": {"cost": [[R.WOOD, 8]], "max_level": 3, "speed": 0.5, "workers": 1,
			"titles": ["药圃", "百草园"]},
		"desc": "种草药（冬季停产）：药剂坊的原料，最终撑起医馆这条民生线",
	},
	{
		"id": &"apothecary", "group": "produce", "sector": "economy", "name": "药剂坊",
		"color": Color(0.6, 0.75, 0.6), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 16], [R.STONE, 8]],
		"produces": true, "inputs": [[R.HERB, 2]], "outputs": [[R.MEDICINE, 1]],
		"interval": 10.0, "workers": 1, "min_era": 3,
		"upgrade": {"cost": [[R.WOOD, 12], [R.STONE, 6]], "max_level": 3, "speed": 0.5, "workers": 1,
			"titles": ["大药剂坊", "药行"]},
		"desc": "草药熬成药剂：造医馆要它，卖 7 金一瓶也是全场最高价",
	},
	{
		"id": &"militia_post", "group": "defense", "sector": "military", "name": "民兵营",
		"color": Color(0.5, 0.35, 0.32), "size": Vector2i(2, 2),
		"cost": [[R.WOOD, 18], [R.STONE, 8]],
		"workers": 2, "trains_guards": true, "min_era": 3,
		"upgrade": {"cost": [[R.WOOD, 14], [R.STONE, 6]], "max_level": 3, "workers": 1,
			"titles": ["大民兵营", "民团"]},
		"desc": "比兵营早两个时代的简易武装：派进来的村民成为卫兵（每天 1 金军饷），撤出即退役",
	},
	{
		"id": &"beacon", "group": "defense", "sector": "military", "name": "烽火台",
		"color": Color(0.75, 0.45, 0.25), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 8], [R.STONE, 10]],
		"produces": false, "workers": 1, "min_era": 3, "scares_wolves": 9.0,
		"upgrade": {"cost": [[R.WOOD, 6], [R.STONE, 8]], "max_level": 3, "scare": 2.0,
			"titles": ["高烽火台", "狼烟台"]},
		"desc": "半径 9 格的驱狼范围（全场最大），石砌不烧柴；有人值守才点得着",
	},
	# ---- 时代Ⅳ：市场与防御 ----
	{
		"id": &"market", "group": "produce", "sector": "economy", "name": "市场",
		"color": Color(0.9, 0.7, 0.3), "size": Vector2i(2, 2),
		"cost": [[R.WOOD, 25], [R.STONE, 10]],
		"produces": false, "workers": 1, "min_era": 4, "auto_sells": true,
		"sell_cap": 20,
		"upgrade": {"cost": [[R.WOOD, 18], [R.STONE, 8]], "max_level": 3, "sell_cap": 10,
			"titles": ["大市场", "商业广场"]},
		"desc": "每天自动卖出保留线以上的富余产物换金币（每市场每天上限 20 金）",
	},
	{
		"id": &"wall", "group": "defense", "sector": "military", "name": "城墙",
		"color": Color(0.45, 0.45, 0.5), "size": Vector2i(1, 1),
		"cost": [[R.STONE, 2]], "min_era": 4,
		"hp": 60, "is_wall": true, "drag_place": true,
		"upgrade": {"cost": [[R.STONE, 3]], "max_level": 3, "hp": 60,
			"titles": ["石墙", "高墙"]},
		"desc": "挡住强盗去路（耐久 60，被拆会坏）；敌人不能翻墙，只能拆墙或绕行",
	},
	{
		"id": &"gate", "group": "defense", "sector": "military", "name": "城门",
		"color": Color(0.55, 0.4, 0.25), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 4], [R.STONE, 2]], "min_era": 4,
		"hp": 80, "is_gate": true, "drag_place": true,
		"upgrade": {"cost": [[R.WOOD, 4], [R.STONE, 3]], "max_level": 3, "hp": 80,
			"titles": ["加固城门", "堡门"]},
		"desc": "村民可以穿行、强盗不能；和城墙围出城区（耐久 80）",
	},
	{
		"id": &"watchtower", "group": "defense", "sector": "military", "name": "箭塔",
		"color": Color(0.5, 0.4, 0.3), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 10], [R.STONE, 8]], "min_era": 4, "workers": 1,
		"shoots_range": 6.0, "shoots_damage": 12, "shoots_interval": 1.5,
		"upgrade": {"cost": [[R.WOOD, 8], [R.STONE, 8]], "max_level": 3, "damage": 6, "range": 1.0,
			"titles": ["高箭塔", "箭楼"]},
		"desc": "有弓箭手在岗时自动射击 6 格内的强盗（12 伤/1.5 秒），优先补刀残血",
	},
	{
		"id": &"barracks", "group": "defense", "sector": "military", "name": "兵营",
		"color": Color(0.55, 0.3, 0.3), "size": Vector2i(2, 2),
		"cost": [[R.WOOD, 30], [R.STONE, 20]], "min_era": 4,
		"workers": 3, "trains_guards": true,
		"upgrade": {"cost": [[R.WOOD, 20], [R.STONE, 15]], "max_level": 3, "workers": 1,
			"titles": ["大兵营", "要塞营"]},
		"desc": "派进来的村民成为卫兵（120 血、主动迎击强盗，每天 1 金军饷）；撤出即退役",
	},
	# ---- 时代Ⅳ 追加：铁矿→铁锭→铁器的重工业链，砖石住宅与医馆，山道 ----
	{
		"id": &"mountain_pass", "group": "resource", "sector": "economy", "name": "山道",
		"color": Color(0.5, 0.46, 0.4), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 2], [R.STONE, 2]], "is_road": true, "road_kind": "pass",
		"drag_place": true, "min_era": 4,
		"desc": "在石林/铁矿脉上凿出可通行的山道（移速 ×1.15）：把被山脊隔开的两片领地连起来",
	},
	{
		"id": &"iron_mine", "group": "resource", "sector": "economy", "name": "铁矿场",
		"color": Color(0.45, 0.4, 0.4), "size": Vector2i(2, 2),
		"cost": [[R.WOOD, 18], [R.STONE, 12]],
		"produces": true, "inputs": [], "outputs": [[R.IRON_ORE, 2]],
		"interval": 9.0, "needs_iron": true, "workers": 2, "min_era": 4,
		"work_radius": 2.0,
		"upgrade": {"cost": [[R.WOOD, 12], [R.STONE, 10]], "max_level": 3, "speed": 0.5,
			"workers": 1, "radius": 1.0, "titles": ["大铁矿场", "矿业行会"]},
		"desc": "开采铁矿石（需邻近铁矿脉）：高地丘陵地形的核心产业",
	},
	{
		"id": &"bloomery", "group": "produce", "sector": "economy", "name": "冶铁炉",
		"color": Color(0.5, 0.3, 0.25), "size": Vector2i(2, 2),
		"cost": [[R.WOOD, 20], [R.STONE, 14], [R.BRICK, 6]],
		"produces": true, "inputs": [[R.IRON_ORE, 2], [R.CHARCOAL, 1]], "outputs": [[R.IRON, 1]],
		"interval": 8.0, "workers": 2, "min_era": 4,
		"upgrade": {"cost": [[R.WOOD, 14], [R.STONE, 10]], "max_level": 3, "speed": 0.5, "workers": 1,
			"titles": ["大冶铁炉", "高炉"]},
		"desc": "铁矿石加木炭炼成铁锭；炉膛要用砖砌，所以砖窑必须先转起来",
	},
	{
		"id": &"smithy", "group": "produce", "sector": "economy", "name": "铁匠铺",
		"color": Color(0.42, 0.42, 0.48), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 16], [R.STONE, 10], [R.IRON, 2]],
		"produces": true, "inputs": [[R.IRON, 1], [R.WOOD, 1]], "outputs": [[R.TOOLS, 1]],
		"interval": 9.0, "workers": 1, "min_era": 4,
		"upgrade": {"cost": [[R.WOOD, 12], [R.STONE, 8]], "max_level": 3, "speed": 0.5, "workers": 1,
			"titles": ["大铁匠铺", "锻造行会"]},
		"desc": "打制铁器：弩塔与骑士营都要它，卖 5 金一件也很划算",
	},
	{
		"id": &"stone_house", "group": "life", "sector": "civic", "name": "石屋",
		"color": Color(0.66, 0.62, 0.55), "size": Vector2i(2, 2),
		"cost": [[R.STONE, 10], [R.BRICK, 6]],
		"produces": false, "housing": 8, "min_era": 4, "drag_place": true,
		"upgrade": {"cost": [[R.STONE, 8], [R.BRICK, 6]], "max_level": 3, "housing": 4,
			"titles": ["联排石屋", "石砌大宅"]},
		"desc": "住 8 名村民（小屋只有 3）：人口破百以后再靠木屋铺地会把整张图占满",
	},
	{
		"id": &"clinic", "group": "life", "sector": "civic", "name": "医馆",
		"color": Color(0.85, 0.9, 0.85), "size": Vector2i(2, 2),
		"cost": [[R.WOOD, 16], [R.STONE, 12], [R.MEDICINE, 4]],
		"produces": false, "workers": 1, "min_era": 4,
		"aura_radius": 8.0, "aura_kind": "health",
		"upgrade": {"cost": [[R.STONE, 10], [R.MEDICINE, 4]], "max_level": 3, "aura": 2.0,
			"titles": ["大医馆", "医院"]},
		"desc": "医护光环：半径 8 格内有住房的村民幸福 +6，覆盖不到 -5（时代Ⅳ起生效）",
	},
	{
		"id": &"ballista_tower", "group": "defense", "sector": "military", "name": "弩塔",
		"color": Color(0.45, 0.38, 0.35), "size": Vector2i(1, 1),
		"cost": [[R.WOOD, 12], [R.STONE, 12], [R.TOOLS, 4]], "min_era": 4, "workers": 1,
		"shoots_range": 8.0, "shoots_damage": 22, "shoots_interval": 2.2,
		"upgrade": {"cost": [[R.STONE, 10], [R.TOOLS, 3]], "max_level": 3, "damage": 8, "range": 1.0,
			"titles": ["重弩塔", "弩台"]},
		"desc": "射程 8 格、22 伤/2.2 秒的重武器：单发比箭塔狠得多，但要先有铁器",
	},
	# ---- 时代Ⅴ：贸易站与城堡 ----
	{
		"id": &"trade_post", "group": "produce", "sector": "economy", "name": "贸易站",
		"color": Color(0.6, 0.65, 0.5), "size": Vector2i(2, 1),
		"cost": [[R.WOOD, 25], [R.STONE, 10]], "min_era": 5,
		"workers": 2,
		# 每天用金币收购资源（[类型, 单价, 日上限]）：给金币持续出口、缓解城堡石料瓶颈
		"auto_buys": [[R.STONE, 2, 10], [R.WOOD, 1, 20]],
		"upgrade": {"cost": [[R.WOOD, 18], [R.STONE, 8]], "max_level": 3, "workers": 1, "buy_budget": 20,
			"titles": ["大贸易站", "商会"]},
		"desc": "每天用金币收购石料（2 金/个，≤10）和木材（1 金/个，≤20）；金币低于 50 不收购",
	},
	{
		# 城堡是三期工程：原先是"攒够 100/80/50 然后点一下就通关"，
		# 中间几十分钟没有任何反馈。拆成地基→主楼→王城三级后，
		# 每一期都立刻给全体幸福加成，攒资源的过程本身有了节奏。
		# 三期总价与原来的一次性造价基本持平（木102 石81 金52）。
		"id": &"castle", "group": "life", "sector": "civic", "name": "城堡",
		"color": Color(0.65, 0.6, 0.7), "size": Vector2i(4, 4),
		"cost": [[R.WOOD, 30], [R.STONE, 24], [R.GOLD, 10]],
		"produces": false, "min_era": 5, "aura_kind": "castle", "castle_bonus": 4,
		"upgrade": {"cost": [[R.WOOD, 24], [R.STONE, 19], [R.GOLD, 14]], "max_level": 3,
			"crown": 3, "titles": ["主楼落成", "王城"]},
		"desc": "三期工程：地基（全体幸福 +4）→ 主楼（+7）→ 王城（+10）；王城落成即加冕为王，此后自由建设",
	},
	# ---- 时代Ⅴ 追加：港口与大学，以及王国级的军事建筑 ----
	{
		"id": &"harbor", "group": "produce", "sector": "economy", "name": "港口",
		"color": Color(0.4, 0.55, 0.62), "size": Vector2i(3, 2),
		"cost": [[R.WOOD, 30], [R.STONE, 18], [R.BRICK, 8]], "min_era": 5,
		"workers": 3, "needs_water": true, "auto_sells": true, "sell_cap": 32,
		"auto_buys": [[R.CLAY, 1, 15], [R.SALT, 2, 8]],
		"upgrade": {"cost": [[R.WOOD, 20], [R.STONE, 14]], "max_level": 3,
			"sell_cap": 14, "buy_budget": 20, "workers": 1, "titles": ["商港", "王国大港"]},
		"desc": "海贸枢纽：每天卖富余产物最多 32 金（市场只有 20），同时用金币收购黏土与海盐",
	},
	{
		"id": &"academy", "group": "life", "sector": "civic", "name": "大学",
		"color": Color(0.55, 0.6, 0.85), "size": Vector2i(3, 3),
		"cost": [[R.WOOD, 30], [R.STONE, 25], [R.BRICK, 10], [R.GOLD, 10]],
		"produces": false, "workers": 2, "min_era": 5,
		"teach_radius": 9.0, "teach_slots": 2,
		"upgrade": {"cost": [[R.STONE, 20], [R.BRICK, 8], [R.GOLD, 8]], "max_level": 3,
			"teach_slots": 1, "teach_radius": 2.0, "titles": ["学院", "王家学府"]},
		"desc": "学堂的王国版：每天点化半径 9 格内的两名村民（学堂只有一名，半径 6）",
	},
	{
		"id": &"bastion", "group": "defense", "sector": "military", "name": "棱堡",
		"color": Color(0.4, 0.4, 0.46), "size": Vector2i(2, 2),
		"cost": [[R.STONE, 24], [R.BRICK, 12], [R.IRON, 6]], "min_era": 5, "workers": 1,
		"hp": 220, "is_wall": true,
		"shoots_range": 6.0, "shoots_damage": 16, "shoots_interval": 1.6,
		"upgrade": {"cost": [[R.STONE, 18], [R.BRICK, 10]], "max_level": 3, "hp": 120, "damage": 6,
			"titles": ["重棱堡", "王国要塞"]},
		"desc": "既是耐久 220 的墙体，又是会射击的炮台：城墙拐角处放一座，强盗就啃不动了",
	},
	{
		"id": &"knight_hall", "group": "defense", "sector": "military", "name": "骑士营",
		"color": Color(0.6, 0.28, 0.3), "size": Vector2i(3, 2),
		"cost": [[R.WOOD, 30], [R.STONE, 24], [R.IRON, 10], [R.LEATHER, 8]], "min_era": 5,
		"workers": 5, "trains_guards": true,
		"upgrade": {"cost": [[R.STONE, 18], [R.IRON, 8]], "max_level": 3, "workers": 2,
			"titles": ["大骑士营", "骑士团"]},
		"desc": "一次能养 5 名卫兵（兵营只有 3）；铁与皮革的最终去向，也是加冕前最后的保险",
	},
]

static func find_by_id(id: StringName) -> Dictionary:
	for d in ALL:
		if d["id"] == id:
			return d
	return {}
